<?php

// DO NOT EDIT THIS FILE, READ README.md TO LEARN HOW TO ADD CUSTOMIZATION TO THIS THEME

include WP_CONTENT_DIR . '/../vendor/autoload.php';

\Timber::$locations = get_template_directory() . '/Resources/views';

new \ClientName\ClientNameTheme();
