<?php

/**
 * DO NOT EDIT THIS FILE, READ README.md TO LEARN HOW TO ADD CUSTOMIZATION TO THIS THEME
 */
include WP_CONTENT_DIR . '/../vendor/autoload.php';

\Timber::$locations = array(
    get_template_directory() . '/Resources/views',
    get_template_directory() . '/Resources/build',
);


new \ClientName\ClientNameTheme();