<?php

/*
 * This file is part of the Wordpress Standard project.
 *
 * Copyright (c) 2015 LIN3S <info@lin3s.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 * 
 * @author Gorka Laucirica <gorka.lauzirika@gmail.com>
 * @author Beñat Espiña <benatespina@gmail.com>
 */

/**
 * DO NOT EDIT THIS FILE, READ README.md TO LEARN HOW TO ADD CUSTOMIZATION TO THIS THEME
 */
include WP_CONTENT_DIR . '/../vendor/autoload.php';

\Timber::$locations = [
    get_template_directory() . '/Resources/views',
    get_template_directory() . '/Resources/build',
];

new \WordpressStandard\WordpressStandardTheme();
