# This file is part of the Wordpress Standard project.
#
# Copyright (c) 2015 LIN3S <info@lin3s.com>
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.
#
# @author Gorka Laucirica <gorka.lauzirika@gmail.com>
# @author Beñat Espiña <benatespina@gmail.com>
# @author Jon Torrado <jontorrado@gmail.com>

-
    controller: WordpressStandard\Controller\DefaultController::indexAction
    type: index

-
    controller: WordpressStandard\Controller\DefaultController::notFoundAction
    type: 404

-
    controller: WordpressStandard\Controller\DefaultController::pageAction
    type: page

-
    controller: WordpressStandard\Controller\PostController::listAction
    type: archive
    slug: post

-
    controller: WordpressStandard\Controller\PostController::showAction
    type: single
    slug: post
