-
    controller: Bizkarra\Controller\DefaultController::indexAction
    type: index

-
    controller: Bizkarra\Controller\DefaultController::notFoundAction
    type: 404

-
    controller: Bizkarra\Controller\DefaultController::pageAction
    type: page
