<?php
/**
 * DO NOT EDIT THIS FILE, READ README.md TO LEARN HOW TO ADD CUSTOMIZATION TO THIS THEME
 */
global $nvlTheme;

define('LIN3S_THEME_VERSION', '0.1');
define('LIN3S_LANG', 'standard-theme');

include 'core/main.php';

$nvlTheme = new NvlTheme();