# This file is part of the WordPress Standard project.
#
# Copyright (c) 2015-2016 LIN3S <info@lin3s.com>
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.
#
# @author Gorka Laucirica <gorka.lauzirika@gmail.com>
# @author Beñat Espiña <benatespina@gmail.com>
# @author Jon Torrado <jontorrado@gmail.com>

-
    controller: AppTheme\Controller\DefaultController::indexAction
    type: front

-
    controller: AppTheme\Controller\DefaultController::notFoundAction
    type: 404

-
    controller: AppTheme\Controller\DefaultController::pageAction
    type: page

-
    controller: AppTheme\Controller\PostController::listAction
    type: home

-
    controller: AppTheme\Controller\PostController::categoryListAction
    type: archive
    posttype: post

-
    controller: AppTheme\Controller\PostController::showAction
    type: single
    posttype: post

-
    controller: AppTheme\Controller\DefaultController::attachmentAction
    type: attachment
